# Generated by Django 4.0.1 on 2022-01-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_titulo', models.CharField(max_length=200)),
                ('curso_contenido', models.TextField()),
                ('curso_publicado', models.DateTimeField(verbose_name='Fecha de publicación')),
            ],
        ),
    ]
